[versions]
activity = "1.12.2"
agp = "9.0.0"
espressoCore = "3.7.0"
guava = "33.5.0-android"
junit = "4.13.2"
junitVersion = "1.3.0"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
